### ISSUE TITLE
I cannot insert targeted country under campaign field and cannot save new campaign

### ISSUE THREAD

**Issue by HerminaC** [oyiptong/splice#271] opened 2015-11-26 13:58 UTC
http://splice_tiles.dev.mozaws.net/ -> Campaign app -> Create new account -> Create new campaign
The drop down list for Country field is empty (no results found), which makes it impossible to save a newly created campaign. Please see attach. Thanks!

![screen shot 2015-11-26 at 2 52 38 pm](https://cloud.githubusercontent.com/assets/7406447/11424512/0a328ac4-944e-11e5-8b79-c6eb2c1b1470.png)

![screen shot 2015-11-26 at 2 52 59 pm](https://cloud.githubusercontent.com/assets/7406447/11424515/1001026e-944e-11e5-8afc-37fa12c08eb0.png)

**Comment by tkiethanom** [comment] 2015-11-26 17:19
Looks like the Init values aren't loading. Can someone look into this since I don't have access to the dev environment.

**Comment by rlr** [comment] 2015-11-30 20:19
The problem is the API call to get the init data is returning a 500 (http://splice_tiles.dev.mozaws.net/api/init/all)

Any ideas @ncloudioj

**Comment by ncloudioj** [comment] 2015-11-30 21:20
@rlr I think we came across this issue when the dev server was down due to the ConnectionPool is Unavailable issue, and that issue has been fixed separately. That being said, the front end should also check the status code of this API in case the backend server is down in the first place. @tkiethanom

**Comment by rlr** [comment] 2015-11-30 22:38
@ncloudioj are you saying the connection pool issue is fixed now? on dev? Because the API is still returning 500: http://splice_tiles.dev.mozaws.net/api/init/all

**Comment by ncloudioj** [comment] 2015-11-30 22:48
@rlr Not yet. Will deploy it once the PR gets r+.

**Comment by ncloudioj** [comment] 2015-12-01 01:50
Hey folks, this is now fixed.

The `api/init/all` kept failing was because I forgot to include a static file in the `MANIFEST.in`. It might also leave a database session behind, so I suspect that was also the cause of the connection pool issue.

**Closed by ncloudioj** 2015-12-01 01:50 UTC
Labels: bug
