### ISSUE TITLE
"fab build_ui" failed during splice deployment

### ISSUE THREAD

**Issue by ncloudioj** [oyiptong/splice#290] opened 2015-12-09 18:03 UTC
@rlr and @tkiethanom  Can anyone take a look at this issue please? https://bugzilla.mozilla.org/show_bug.cgi?id=1230670 

It also failed to build locally. Looks like it has to do with the new dependent libraries.

Thanks.

**Comment by tkiethanom** [comment] 2015-12-09 18:15
Ok I'm on it.

**Comment by tkiethanom** [comment] 2015-12-09 18:28
Make sure the history package is the correct version. In `package.json` the package is set to 1.13.1. You should be able to just run `npm install history` on the server.

**Comment by tkiethanom** [comment] 2015-12-09 18:35
Oh sorry, the problem is in `ui` not `front_end`.

**Comment by rlr** [comment] 2015-12-09 18:36
I'll take a look.

**Comment by tkiethanom** [comment] 2015-12-09 18:37
The package versions just need to be locked

**Comment by rlr** [comment] 2015-12-09 18:51
Submitted PR #291

**Comment by rlr** [comment] 2015-12-09 18:56
This should be fixed now bf3ef59e9d83ed64babd60698712617e3e7a1229

**Closed by rlr** 2015-12-09 18:56 UTC
Labels: bug, splice 2
